# AUTOGENERATED! DO NOT EDIT! File to edit: app.ipynb.

# %% auto 0
__all__ = ['learner', 'categories', 'image', 'label', 'examples', 'interface', 'classify_image']

# %% app.ipynb 2
import gradio as gr
from fastai.vision.all import *

# %% app.ipynb 5
learner = load_learner('model/flood_classifier.pkl')

# %% app.ipynb 7
categories = ('Not Flooded', 'Flooded')

def classify_image(image):
    prediction, index, probabilities = learner.predict(image)
    return dict(zip(categories, map(float, probabilities)))

# %% app.ipynb 9
image = gr.Image()
label = gr.Label()
examples = [str(image_path) for image_path in Path('images/example_images')
.rglob('*.jpeg')]

# %% app.ipynb 11
interface = gr.Interface(fn=classify_image, inputs='image', outputs='label', examples=examples)
interface.launch(inline=False)
